spring:
  cloud:
    config.discovery.enabled: true
  application:
    name: undertow-reverse-proxy

server:
  port: 8080
  undertow:
    accesslog:
      dir: target/logs
      pattern: combined
      enabled: true
  compression:
    enabled: true
    min-response-size: 1

    
zuul:
  routes:
    wso2demo1:
      path: /wso2demo1/**
      stripPrefix: false
      service-id: wso2demo1

ribbon.eureka.enabled: false
